### ISSUE TITLE
No entities and module notfound error

### ISSUE THREAD

**Issue by DKFR67** [aalmazanarbs/hassio_aldes#10]
First off all many thanks for your great and useful integration.

Since last update, my VMC has no entities and I have the errors while loading the module.
All worked fine with your March update. I tried your last updated code without results. 

Can you give me advices to fix my problem, or perhaps can you fix your code?

Thanks in advance
![Error Log](https://user-images.githubusercontent.com/123078627/232837589-84ff11c3-0b1f-418c-a608-04220b5e4ccf.jpg)
![No Entity](https://user-images.githubusercontent.com/123078627/232837593-5e9e4a0e-1ce6-4e9a-9480-a3b72aaba551.jpg)

**Comment by aalmazanarbs** [comment]
Hi @DKFR67,

The error you are reporting is very weird.

- The last update only modify the connection with Aldes API so the error with entities is unexpected.
- The integration name display: Aldes - email account but your screenshot show something not related.
- The error report aldes/group.py, aldes/cast.py...but these files are not present in this integration. Also, custom_components.hassio_aldes-master.logbook is weird since the integration must be in custom_components/aldes and .logbook is not present in this integration again.

Please, check you files, HA version and other general installation problems and come back with news :)

**Comment by DKFR67** [comment]
Hi @aalmazanarbs 

Thank you for your answer.
The error was fixed by renaming the directory as "aldes" instead of "hassio_aldes-master" (with older versions of home assistant this gave no errors ...)


To see my VMC "EASY_HOME_PREMIUM", I had to use an old part of your code, without the "is_product_supported" parts
![VMC](https://user-images.githubusercontent.com/123078627/233020180-09237b6a-1c30-4f51-8fa3-52c0d883cfca.png)
.

**Comment by aalmazanarbs** [comment]
@DKFR67 nice, good news

So, if your product if fully compatible with this integration I can add as supported product. Could you tell the real name of your product or the output for the endpoint `/aldesoc/v5/users/me/products`. Is your product compatible with these five modes: `Holidays`, `Daily`, `Boost`, `Guest` and `Air Prog`?

**Comment by DKFR67** [comment]
Where can I find  the output for the endpoint /aldesoc/v5/users/me/products
?
My product is compatible with the five modes: Holidays, Daily, Boost, Guest
and Air Prog.

**Comment by aalmazanarbs** [comment]
@DKFR67 you need to make a curl with your credentials to https://aldesiotsuite-aldeswebapi.azurewebsites.net/oauth2/token to get an access token.
Then with the credentials make a curl to https://aldesiotsuite-aldeswebapi.azurewebsites.net/aldesoc/v5/users/me/products to get information about your products in order to get reference and display name for your product.

**Comment by DKFR67** [comment]
@aalmazanarbs/hassio_aldes
***@***.***>

I tried, but aldes API returns the code above when I request the token ...

{
  "error": "invalid_request",
  "error_description": "The specified HTTP method is not valid.",
  "error_uri": "https://documentation.openiddict.com/errors/ID2084"
}

My syntax is :  curl -v -u 'my_user_name:my_password'
https://aldesiotsuite-aldeswebapi.azurewebsites.net/oauth2/token

**Comment by aalmazanarbs** [comment]
@DKFR67 here you have the curls

```
curl --location 'https://aldesiotsuite-aldeswebapi.azurewebsites.net/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'username=your-user-name' \
--data-urlencode 'password=your-password'
```

```
curl --location 'https://aldesiotsuite-aldeswebapi.azurewebsites.net/aldesoc/v5/users/me/products' \
--header 'Authorization: Bearer the-access-token-of-previous-request'
```

**Comment by Saeglopur76** [comment]
Hello @DKFR67,
Did you fix your problem? Are you able to discover your Aldes product with the last @aalmazanarbs release?
If yes, could you confirm and share your fix with the HA community.
If not, I guess you only have to add your product name in the product.py file.
You could try something like :

_DISPLAY_NAMES: Final = {
    'INSPIRAIR_HOME_S' : 'InspirAIR® Home S',
    'EASY_HOME_CONNECT' : 'EASYHOME PureAir Compact CONNECT',
    'DEE_FLY_CUBE' : 'Dee Fly Cube'**,**
    **'EASY_HOME_PREMIUM' : 'EasyHOME PREMIUM'**

 (don't forget the coma at the end of the previous line!) ;)

Best Regards

**Comment by DKFR67** [comment]
Hello,

With last release and adding the line *'EASY_HOME_PREMIUM' : 'EASYHOME
Premium' *into the code, all work perfect.

Le jeu. 1 juin 2023 à 22:34, Saeglopur76 ***@***.***> a
écrit :

**Comment by aalmazanarbs** [comment]
Hi @DKFR67, please create a pull request with your product since you have tested it works :)
