### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by msaario** [aalmazanarbs/hassio_aldes#5]
Good morning, I just got my AldesConnect Box connected to cloud and try to add the integration as custom component. I see it normally in Home Assistant but once selected, the config flow cannot be opened with following error:

> Config flow could not be loaded: {"message":"Invalid handler specified"}

In logs I see further information:

> Logger: homeassistant.config_entries
> Source: config_entries.py:852 
> First occurred: 30 January 2023 at 21:26:04 (2 occurrences) 
> Last logged: 07:12:43
> 
> Error occurred loading configuration flow for integration aldes: No module named 'api'

I am running version 2023.1.7 of HA on MacOS and I installed manually unzipping project to custom_components. Upon searching web for this error, it seems to affect some users with various custom integrations.

Meanwhile this error prevents adding, is it possible to manually add credentials to configuration.yaml?

Thank you, let me know if any further information is needed to troubleshoot.

**Comment by aalmazanarbs** [comment]
Hi @msaario,

I am running 2023.1.7 of HA on Raspbian and with fresh download of the component is working fine. Please check that the root of this project is under `config/custom_components/aldes` and the code is not modified (in order to try without HA some modifications are needed but must be removed for HA).
Thinking about the error `No module named 'api'`, it seems that it is a error related with Python and not with HA. Maybe the version. Maybe the load of python modules does not work the same on linux as it does on mac os.

HA is trying to remove YAML configuration for the config flows so it is very strange that it is not working and this integration will not support it at the moment.

**Comment by msaario** [comment]
Hi @aalmazanarbs 
Thanks for quick response, I have verified that location is correct and code is not modified.

The operating system could be causing the issue. I am using venv virtual python environment within macos command line and running HA as service.

I will later try a new installation on Raspberry Pi to see if that will solve the issue.

**Comment by aalmazanarbs** [comment]
Ok @msaario, try it with supervised installation. I will try it on mac os as well.

**Comment by msaario** [comment]
I confirm that with Home Assistant Supervised this error does not occur neither on Raspberry Pi nor MacOS virtual machine. It must be related to some limitations on Home Assistant Core on MacOS. You can close this issue as solved.

Thanks for help!
