### ISSUE TITLE
Oauth2Token.__init__() missing 1 required positional argument: 'refresh_token'

### ISSUE THREAD

**Issue by msaario** [aalmazanarbs/hassio_aldes#9]
Hi @aalmazanarbs 
I started getting error of Oauth2Token today after power was cut off for a while.
![image](https://user-images.githubusercontent.com/119809442/231443165-cf94b732-9105-4180-bfa8-c5e2a689d293.jpeg)

Previously same configuration worked and I can still use credentials in AldesConnect app. When I try to add the integration again (disabling old configuration) I get following error:
![image](https://user-images.githubusercontent.com/119809442/231443516-0a33926a-e99f-4274-aab9-fa4107c7fe8f.jpeg)

Do you have any advise how to investigate and solve this?

Many thanks!

**Comment by aalmazanarbs** [comment]
Hi @msaario,

> I can not reproduce the issue you report. Does you problem continues? Maybe it was a temporal problem with Aldes API.
Maybe the problem is related with your password or with your Aldes account settins. Could you check or give more information?
If the problem is solved, please close the topic.

I have managed to reproduce the issues, my installation continued to work until the token expired and now I have the same error. I think it is related to Aldes API change since they does not return `refresh_token` anymore. I will try to fix it and come back with news.

**Comment by aalmazanarbs** [comment]
The commit https://github.com/aalmazanarbs/hassio_aldes/commit/ed2f6f83f93048e961ff204452a69b7ebced0383 fix the issue. Please copy new code from master and restastart HA.
